name: SupremeTitan
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25425
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#17140f'
    - '#c0cad3'
    - '#434345'
    - '#fc8e7e'
  brandStrength: 0.02473404724150896
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
