favicon: null
name: Titan Gym Chicago
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#25282D'
    - '#FEFFFF'
    - '#A18E70'
    - '#465A73'
    - '#A9509D'
  lightness: 0.6875
typography_spectrum: 0.1090225
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.8190118
analytics:
  twitter: null
  google: null
  facebook: null
