name: Titan Gym Chicago
favicon: null
layout_spectrum: 0.8190118
typography_spectrum: 0.1090225
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Best gym in Chicago - Krav Maga, Martial Arts, Fitness, and Yoga'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#25282D'
    - '#FEFFFF'
    - '#A18E70'
    - '#465A73'
    - '#A9509D'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
